//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buca.AutoUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buca.AutoUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner_auto_update {
            get {
                object obj = ResourceManager.GetObject("banner_auto_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tốc độ tải {0}/s.
        /// </summary>
        internal static string DownloadSpeedMessage {
            get {
                return ResourceManager.GetString("DownloadSpeedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra tính toàn vẹn.
        /// </summary>
        internal static string FileIntegrityCheckFailedCaption {
            get {
                return ResourceManager.GetString("FileIntegrityCheckFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có một số lỗi trong quá trình kiểm tra tính toàn vẹn của tệp tin.
        /// </summary>
        internal static string FileIntegrityCheckFailedMessage {
            get {
                return ResourceManager.GetString("FileIntegrityCheckFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hỗ trợ thuật toán băm.
        /// </summary>
        internal static string HashAlgorithmNotSupportedCaption {
            get {
                return ResourceManager.GetString("HashAlgorithmNotSupportedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuật toán băm được cung cấp trong tệp tin XML không được hỗ trợ.
        /// </summary>
        internal static string HashAlgorithmNotSupportedMessage {
            get {
                return ResourceManager.GetString("HashAlgorithmNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo cập nhật.
        /// </summary>
        internal static string UpdateCheckFailedCaption {
            get {
                return ResourceManager.GetString("UpdateCheckFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi trong quá trình tìm kiếm phiên bản cập nhật trên máy chủ. Xin vui lòng kiểm tra lại kết nối internet.
        /// </summary>
        internal static string UpdateCheckFailedMessage {
            get {
                return ResourceManager.GetString("UpdateCheckFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo cập nhật.
        /// </summary>
        internal static string UpdateUnavailableCaption {
            get {
                return ResourceManager.GetString("UpdateUnavailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên bản hiện tại trên máy tính của bạn là phiên bản mới nhất. Xin vui lòng kiểm tra lại sau.
        /// </summary>
        internal static string UpdateUnavailableMessage {
            get {
                return ResourceManager.GetString("UpdateUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZipExtractor {
            get {
                object obj = ResourceManager.GetObject("ZipExtractor", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
